model:
  channels: 32 # number of feature maps (filters)
  num_blocks: 7 #layers in the neural network model
  semantic_classes: 3
  instance_classes:  2
  sem2ins_classes: [0,1,2]
  semantic_only: False
  semantic_weight: False
  with_coords: True
  ignore_label: -100
  voxel_scale: 5
  use_spp_pool: True
  filter_bg_thresh: 0.3
  iterative_sampling: True
  instance_head_cfg:
    num_dyco_layer: 2 # 3 the weight and bias configurations are calculated based on
    dec_dim: 128
    n_sample_pa1: 4096 #2048
    n_queries: 256 # 256
    radius_scale: 1
    radius: 0.3 #0.4
    neighbor: 48   #32
  test_cfg:
    x4_split: True
    logit_thresh: 0.0
    score_thresh: 0.5 #0.5 
    npoint_thresh: 500 #400
    type_nms: 'standard'
    topk: -1
    nms_threshold: 0.2

  fixed_modules: ['input_conv', 'unet', 'output_layer', 'semantic_linear', 'offset_linear', 'offset_vertices_linear', 'box_conf_linear']

data:
  train:
    type: 's3dis'
    data_root: 'dataset/s3dis/'
    prefix: ['Area_1']
    suffix: '_inst_nostuff'
    repeat: 20
    training: True
    voxel_cfg:
      scale: 5
      spatial_shape: [256, 2048] #[128, 512] 
      max_npoint: 300000  
      min_npoint: 50
  test:
    type: 's3dis'
    data_root: 'dataset/s3dis/'
    prefix: 'Area_5'
    suffix: '_inst_nostuff'
    training: False
    voxel_cfg:
      scale: 5
      spatial_shape: [256, 2048] #[128, 512]
      max_npoint: 300000  
      min_npoint: 50


dataloader:
  train:
    batch_size: 12
    num_workers: 0
  test:
    batch_size: 1
    num_workers: 0

optimizer:
  type: 'AdamW'
  lr: 0.01
  weight_decay: 0.001 # discouraging large weights and improving generalization.

save_cfg:
  semantic: True
  offset: False
  instance: True
  offset_vertices: False
  nmc_clusters: False
  object_conditions: False

fp16: False  # Temporarily disable mixed precision
epochs: 120
step_epoch: 5 #epoch will reduce every 5 epoch
save_freq: 5
pretrain: 'pretrains/s3dis/pretrain_s3dis_area5.pth'
work_dir: ''
